DROP TABLE IF EXISTS drones CASCADE;
DROP TABLE IF EXISTS props CASCADE;
DROP TABLE IF EXISTS batteries CASCADE;
DROP TABLE IF EXISTS frames CASCADE;
DROP TABLE IF EXISTS cameras CASCADE;
DROP TABLE IF EXISTS flight_controllers CASCADE;
DROP TABLE IF EXISTS motors CASCADE;

CREATE TABLE motors (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	model VARCHAR(255),
	kv_rating VARCHAR(255)
);

CREATE TABLE flight_controllers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	model VARCHAR(255),
	channel_count INTEGER,
	control_link_protocol VARCHAR(255) NOT NULL,
	control_mode VARCHAR(255) NOT NULL
);

CREATE TABLE cameras (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	model VARCHAR(255),
	resolution_mp INTEGER
);

CREATE TABLE frames (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	model VARCHAR(255),
	material VARCHAR(255)
);

CREATE TABLE batteries (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	model VARCHAR(255),
	capacity_mah INTEGER
);

CREATE TABLE props (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	model VARCHAR(255),
	spec VARCHAR(255)
);

CREATE TABLE drones (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255),
	prop_id BIGINT,
	motor_id BIGINT,
	flight_controller_id BIGINT,
	camera_id BIGINT,
	frame_id BIGINT,
	battery_id BIGINT,
	video_link_type VARCHAR(255) NOT NULL,
	props_count INTEGER NOT NULL,
	weight_grams INTEGER,
	wheelbase_mm INTEGER,
	flight_time_minutes INTEGER,
	is_deleted BOOLEAN,
	CONSTRAINT fk_drones_prop FOREIGN KEY (prop_id) REFERENCES props(id),
	CONSTRAINT fk_drones_motor FOREIGN KEY (motor_id) REFERENCES motors(id),
	CONSTRAINT fk_drones_flight_controller FOREIGN KEY (flight_controller_id) REFERENCES flight_controllers(id),
	CONSTRAINT fk_drones_camera FOREIGN KEY (camera_id) REFERENCES cameras(id),
	CONSTRAINT fk_drones_frame FOREIGN KEY (frame_id) REFERENCES frames(id),
	CONSTRAINT fk_drones_battery FOREIGN KEY (battery_id) REFERENCES batteries(id)
);